### ISSUE TITLE
exclamation mark remains after installing client

### ISSUE THREAD

**Issue by kris-deridder** [thestarksolutions/Second-Browser-Client#2]
Hello Steven,
I have followed your installation instructions of extension and client, but the exclamation mark remains. I'm on Win8.1 and in the extension options no other browser is yet available.
When yet trying to add a browser, the "Add" or "Save" buttons have no effect. I learned from your other comments that the extension may not detect the client. Any way to check status of client installation? Any other settings that may be needed to activate the extension?
Thanks in advance,
Kris

**Comment by thestarksolutions** [comment]
Hi Kris, 

Not sure why it's not working, but couple questions:

1. After installing the client, did you move the folder somewhere else, or delete it? You might try running uninstall_host.bat and install_host.bat again, but make sure not to move the folder after installing the client.
2. Did you install the version of the client with the portable python?
3. If you are familiar with regedit, you can check that the client is registered with Chrome's native messaging host by going to regedit -> HKEY_CURRENT_USER -> Software -> Google -> Chrome -> NativeMessagingHosts. You should see com.stark.second_browser_client there.

I don't have a Win8.1 machine to troubleshoot on, but let me know about the above and maybe we can figure it out.

Steven

**Comment by kris-deridder** [comment]
Hello Steven,
Wow, swift reply ☺.

1.     Didn’t move anything; you warned on this sufficiently in your instructions ;-). Uninstalling and reinstalling: no improvement.

Install screen [cid:image002.png@01D3AB56.E5803C40]

2.     Portable python: yes

3.     Registry entry available
I guess this doesn’t help you much… Any other ideas?
K

**Comment by thestarksolutions** [comment]
Hey Kris, yeah still unclear why its not working. 

One more thing to check is that the python bundled is actually working. If you navigate to the py27 folder in windows explorer, hold shift and right click in the window and select 'open command prompt here'. Then from the command prompt type 'python.exe' (no quotes), do you get an active python shell?

I'm unable to replicate the problem, I've tested it on win7, win10, and win server 2012 with success so not sure whats going on.

I created a separate branch with some logging as well if you'd like to keep pursuing the issue, download the issue-2 branch from the github repo instead of master. Uninstall the old, then run through the same install steps and try to use the extension. There will be a client_log file created in the same folder as the client (assuming the python is working..). You can send that to me to review and we can go from there.

Steven

**Comment by kris-deridder** [comment]
Aha!
[cid:image001.png@01D3ABCE.54690DE0]
I think I’ll have to create a request to my IT guy…
Thank you, Steven, always great to work with capable people!
K
